// AUTO-GENERATED by scripts/measure-frames.py — face/bust framing per tall sprite,
// measured from each sprite's alpha silhouette. Re-run after adding/replacing portraits.
// Hand-tune via the OVERRIDES map in the script (dx/dy/dzoom), not here.
export interface PortraitFrame { top: number; left: number; height: number }

export const DEFAULT_FRAME: PortraitFrame = {"top": -0.0, "left": 50.0, "height": 294.3};

export const PORTRAIT_FRAMES: Record<string, PortraitFrame> = {
  "alice": {
    "top": -0.0,
    "left": 62.3,
    "height": 294.4
  },
  "aria": {
    "top": -0.0,
    "left": 50.2,
    "height": 294.1
  },
  "astra": {
    "top": -0.0,
    "left": 55.3,
    "height": 294.3
  },
  "burnice": {
    "top": -0.0,
    "left": 36.9,
    "height": 294.0
  },
  "cissia": {
    "top": -0.0,
    "left": 30.6,
    "height": 294.1
  },
  "dialyn": {
    "top": -0.0,
    "left": 53.9,
    "height": 294.4
  },
  "ellen": {
    "top": -0.0,
    "left": 6.3,
    "height": 294.3
  },
  "evelyn": {
    "top": -0.0,
    "left": 33.7,
    "height": 294.4
  },
  "janedoe": {
    "top": -0.0,
    "left": 56.5,
    "height": 294.3
  },
  "jufufu": {
    "top": -0.0,
    "left": 59.8,
    "height": 294.1
  },
  "lighter": {
    "top": -0.0,
    "left": 52.3,
    "height": 294.3
  },
  "lucia": {
    "top": -0.0,
    "left": 67.5,
    "height": 294.3
  },
  "miyabi": {
    "top": -130.0,
    "left": 63.0,
    "height": 500.0
  },
  "nangongyu": {
    "top": -0.0,
    "left": 51.8,
    "height": 294.3
  },
  "seed": {
    "top": -0.0,
    "left": 37.1,
    "height": 294.3
  },
  "soldier0anby": {
    "top": -0.0,
    "left": 53.8,
    "height": 294.3
  },
  "sunna": {
    "top": -0.0,
    "left": 49.5,
    "height": 293.8
  },
  "trigger": {
    "top": -0.0,
    "left": 57.1,
    "height": 294.1
  },
  "velina": {
    "top": -0.0,
    "left": 77.3,
    "height": 294.1
  },
  "vivian": {
    "top": -0.0,
    "left": 23.3,
    "height": 294.0
  },
  "yeshunguang": {
    "top": -0.0,
    "left": 62.2,
    "height": 294.2
  },
  "yeshunguang_enlightened": {
    "top": -0.0,
    "left": 49.7,
    "height": 294.2
  },
  "yidhari": {
    "top": -0.0,
    "left": 55.6,
    "height": 294.1
  },
  "yixuan": {
    "top": -0.0,
    "left": 49.5,
    "height": 294.3
  },
  "yuzuha": {
    "top": -0.0,
    "left": 35.1,
    "height": 294.2
  },
  "zhao": {
    "top": -0.0,
    "left": 52.5,
    "height": 294.3
  }
};

export function portraitFrame(slug: string): PortraitFrame {
  return PORTRAIT_FRAMES[slug] ?? DEFAULT_FRAME;
}
