// GENERATED by scripts/build-tokens.mjs from tokens/tokens.json — do not edit by hand.
export const ELEMENT_COLORS = {
  "Physical": "#E0A526",
  "Fire": "#E5482E",
  "Ice": "#4DB3E6",
  "Frost": "#9AD7F2",
  "Electric": "#3A6BFF",
  "Ether": "#E0408F",
  "Wind": "#2DBE8C",
  "Lumiflux": "#A866F2",
  "Honed Edge": "#8E9BA8",
  "Auric Ink": "#C9A13B"
} as const;
export type Element = keyof typeof ELEMENT_COLORS;
export const GRADES = {
  "S": {
    "bg": "#F2B705",
    "fg": "#17130F",
    "medal": "legend"
  },
  "A": {
    "bg": "#E8501C",
    "fg": "#17130F",
    "medal": "master"
  },
  "B": {
    "bg": "#5B3FD9",
    "fg": "#FFFFFF",
    "medal": "diamond"
  },
  "C": {
    "bg": "#2E7D4F",
    "fg": "#FFFFFF",
    "medal": "gold"
  },
  "D": {
    "bg": "#5F564B",
    "fg": "#FFFFFF",
    "medal": "silver"
  },
  "E": {
    "bg": "#3A332B",
    "fg": "#FFFFFF",
    "medal": null
  }
} as const;
export type Grade = keyof typeof GRADES;
export const SLANT = 0.29;
export const MOTION = {
  "duration": {
    "tick": "200ms",
    "quick": "250ms",
    "base": "350ms",
    "swap": "600ms",
    "tape": "620ms",
    "wipe": "800ms",
    "cover": "1000ms",
    "bar": "1100ms",
    "tracking": "850ms"
  },
  "ease": {
    "out": "cubic-bezier(.2,.8,.2,1)",
    "inout": "cubic-bezier(.65,0,.25,1)",
    "wipe": "cubic-bezier(.77,0,.18,1)",
    "bounce": "cubic-bezier(.3,1.6,.5,1)",
    "tracking": "cubic-bezier(.45,0,.55,1)"
  },
  "stagger": {
    "tight": "60ms",
    "deal": "90ms",
    "segment": "35ms",
    "cell": "180ms"
  }
} as const;
