# Measure a face/bust framing for each tall sprite from its alpha silhouette, so the square
# roster tile zooms to the head instead of cover-fitting the whole (variably-composed) sprite.
#   python scripts/measure-frames.py            # write src/lib/portrait-frames.ts
#   python scripts/measure-frames.py --debug    # also print per-sprite measurements
#   python scripts/measure-frames.py --sheet    # also render scripts/.frames-contact.png for QA
#
# Model (mirrors wuwa-dashboard-next/src/lib/portraits.ts): the tile is a square overflow:hidden
# cell; the sprite is an <img> sized by height% (width auto), translateX(-50%), at left%/top%.
# We frame a bust band = top BUST_FRAC of the alpha figure (+ a little headroom) to fill the cell,
# centered horizontally on the upper-body centroid. Normalizing against the FIGURE's alpha height
# (not the raw canvas) makes the head land at a consistent size regardless of sprite padding/scale.
import os, sys, json
import numpy as np
from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TALL = os.path.join(ROOT, "public", "assets", "tall")
OUT = os.path.join(ROOT, "src", "lib", "portrait-frames.ts")
SHEET = os.path.join(ROOT, "scripts", ".frames-contact.png")
DEBUG = "--debug" in sys.argv
DO_SHEET = "--sheet" in sys.argv

BUST_FRAC = 0.34       # band height = BUST_FRAC * figure-alpha-height (head + shoulders/upper chest)
HEADROOM = 0.05        # extra band above head-top, as a fraction of figure height
ALPHA_T = 16           # alpha above this counts as opaque (figure)

# per-slug ABSOLUTE frame overrides for sprites whose composition fools the silhouette heuristic
# (companions/props inflate the alpha box). Any key present replaces the measured value.
#   miyabi: a shadow-wolf companion fills the top ~25%, so the auto-frame centers on the wolf and
#   shrinks her real face (≈33% down, slightly left) to a low blob. Hand-framed on her bust.
OVERRIDES: dict[str, dict] = {
    "miyabi": {"top": -130.0, "left": 63.0, "height": 500.0},
}


def measure(path):
    im = Image.open(path).convert("RGBA")
    a = np.asarray(im)[:, :, 3]
    H, W = a.shape
    mask = a > ALPHA_T
    rows = np.where(mask.any(axis=1))[0]
    cols = np.where(mask.any(axis=0))[0]
    if len(rows) == 0 or len(cols) == 0:
        return None
    y0, y1 = int(rows[0]), int(rows[-1])
    fig_h = y1 - y0

    band_top = max(0.0, y0 - HEADROOM * fig_h)
    band_bottom = y0 + BUST_FRAC * fig_h
    band_px = band_bottom - band_top

    # horizontal center = alpha centroid of the bust band (head + shoulders)
    bbot = min(int(band_bottom) + 1, H)
    sub = mask[y0:bbot]
    ys, xs = np.where(sub)
    face_cx = float(xs.mean()) if len(xs) else (cols[0] + cols[-1]) / 2

    height_pct = H / band_px * 100.0
    top_pct = -(band_top / band_px) * 100.0
    left_pct = 50.0 - ((face_cx - W / 2) / band_px) * 100.0

    return dict(top=top_pct, left=left_pct, height=height_pct,
                W=W, H=H, y0=y0, fig_h=fig_h, band_top=band_top, band_px=band_px, face_cx=face_cx)


def apply_override(slug, fr):
    ov = OVERRIDES.get(slug)
    if not ov:
        return fr
    fr = dict(fr)
    fr.update(ov)
    return fr


def main():
    raw, frames = {}, {}
    for fn in sorted(os.listdir(TALL)):
        if not fn.endswith(".webp"):
            continue
        slug = fn[:-5]
        m = measure(os.path.join(TALL, fn))
        if not m:
            continue
        raw[slug] = m
        fr = apply_override(slug, {k: round(m[k], 1) for k in ("top", "left", "height")})
        frames[slug] = {k: round(v, 1) for k, v in fr.items()}
        if DEBUG:
            print(f"{slug:24} top={frames[slug]['top']:>7} left={frames[slug]['left']:>6} "
                  f"height={frames[slug]['height']:>6}  W={m['W']} H={m['H']} y0={m['y0']} cx={m['face_cx']:.0f}")

    import statistics as st
    default = {"top": round(st.median(f["top"] for f in frames.values()), 1),
               "left": 50.0,
               "height": round(st.median(f["height"] for f in frames.values()), 1)}

    body = (
        "// AUTO-GENERATED by scripts/measure-frames.py — face/bust framing per tall sprite,\n"
        "// measured from each sprite's alpha silhouette. Re-run after adding/replacing portraits.\n"
        "// Hand-tune via the OVERRIDES map in the script (dx/dy/dzoom), not here.\n"
        "export interface PortraitFrame { top: number; left: number; height: number }\n\n"
        f"export const DEFAULT_FRAME: PortraitFrame = {json.dumps(default)};\n\n"
        "export const PORTRAIT_FRAMES: Record<string, PortraitFrame> = "
        + json.dumps(frames, indent=2) + ";\n\n"
        "export function portraitFrame(slug: string): PortraitFrame {\n"
        "  return PORTRAIT_FRAMES[slug] ?? DEFAULT_FRAME;\n}\n"
    )
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(body)
    print(f"\nwrote {OUT} — {len(frames)} frames, default={default}")

    if DO_SHEET:
        render_sheet(raw, frames)


def render_sheet(raw, frames):
    # Crop the exact square window the CSS tile shows (side = band_px, centered on face_cx,
    # top at band_top), resize to a thumb, label, and tile into a grid for pixel QA.
    THUMB, COLS, PAD = 150, 6, 8
    slugs = sorted(raw.keys())
    rows = (len(slugs) + COLS - 1) // COLS
    sheet = Image.new("RGB", (COLS * (THUMB + PAD) + PAD, rows * (THUMB + PAD + 14) + PAD), (18, 14, 22))
    draw = ImageDraw.Draw(sheet)
    try:
        font = ImageFont.truetype("arial.ttf", 11)
    except Exception:
        font = ImageFont.load_default()
    for i, slug in enumerate(slugs):
        m = raw[slug]
        fr = frames[slug]
        im = Image.open(os.path.join(TALL, slug + ".webp")).convert("RGBA")
        # invert the CSS frame back to a native square window so the thumb == the real tile
        scale = (fr["height"] / 100.0) / m["H"]          # display-per-native at tile side = 1
        win = 1.0 / scale                                # native px shown across the (unit) tile
        cx = (0.5 - fr["left"] / 100.0) * win + m["W"] / 2
        ty = (-fr["top"] / 100.0) * win
        left = cx - win / 2
        crop = im.crop((int(left), int(ty), int(left + win), int(ty + win)))
        bg = Image.new("RGBA", crop.size, (26, 20, 31, 255))
        bg.alpha_composite(crop)
        thumb = bg.convert("RGB").resize((THUMB, THUMB))
        cxp = PAD + (i % COLS) * (THUMB + PAD)
        cyp = PAD + (i // COLS) * (THUMB + PAD + 14)
        sheet.paste(thumb, (cxp, cyp))
        draw.text((cxp + 2, cyp + THUMB + 1), slug[:20], fill=(210, 200, 215), font=font)
    sheet.save(SHEET)
    print(f"wrote {SHEET} — {len(slugs)} crops")


if __name__ == "__main__":
    main()
